config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/articles" => "articles#index", as: "articles"
  root 'authors#index'

  resources :authors do
    resources :works do
      resources :articles, except: [:index]
      resources :chapters do
        resources :sections
      end
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :work
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :find_parents, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  def index
    @works = Work.joins(:articles).uniq.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params

    if @article.save
      flash[:success] = "Article created!"
      redirect_to author_work_article_path(@author, @work, @article)
    else
      flash[:error] = "It didn't work!"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update article_params
      flash[:success] = "The article was successfully saved!"
      redirect_to author_work_article_path(@author, @work, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :work_id)
  end

  def find_article
    @article = Article.friendly.find(params[:id])
  end

  def find_parents
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:work_id])
  end
end

app/views/articles/_form.html.erb
<div class="wrapper">
  <%= simple_form_for [@author, @work, @article], html: {class: "new-form"} do |f| %>
    <%= f.hidden_field :work_id, value: @work.id %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="banner">
  <div class="center">
    <h1>Add a new article</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<div class="banner">
  <div class="center">
    <h1>All articles</h1>
    <%= image_tag "plato.png" %>
  </div>
</div>

<div class="wrapper">
  <section class="text">
  <% @works.group_by(&:author).each do |author, works| %>
    <h1><%= author.name %></h1>
    <% works.each do |work| %>
      <h2><%= link_to work.name, author_work_path(author, work) %></h2>
      <ul>
      <% work.articles.each do |article| %>
        <li><%= link_to article.title, author_work_article_path(author, work, article) %></li>
      <% end %>
      </ul>
    <% end %>
  <% end %>
  </section>
</div>

app/views/articles/new.html.erb
<div class="banner">
  <div class="center">
    <h1>Add a new article</h1>
  </div>
</div>

<%= render partial: 'form' %> 

app/views/articles/show.html.erb
<div class="banner">
  <div class="center">
    <h1><%= @article.title %></h1>
    <% if signed_in? %>
      <ul>
        <li><%= link_to "Edit article", edit_author_work_article_path(@article.work.author, @article.work, @article) %></li>
        <li><%= link_to "Delete article", author_work_article_path(@author), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    <% end %>
    <%= image_tag @article.work.author.bust.url(:normal) %>
  </div>
</div>
<div class="wrapper">
  <section class="text">
    <%= markdown @article.content %>
  </section>
</div>