config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/articles" => "articles#index", as: "articles"
  root 'authors#index'

  resources :authors do
    resources :works do
      resources :articles, except: [:index]
      resources :chapters do
        resources :sections
      end
    end
  end
end

app/models/work.rb
class Work < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :author
  has_many :chapters, dependent: :destroy
  has_many :articles, dependent: :destroy

  validates :name, presence: true
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :require_login, except: [:show]

  def show
    @work = Work.friendly.find(params[:id])
  end

  def new
    @author = Author.friendly.find(params[:author_id])
    @work = Work.new
  end

  def create
    @author = Author.friendly.find(params[:author_id] )
    @work = Work.new(work_params)

    if @work.save
      redirect_to author_work_path(@author, @work)
    else
      render 'new'
    end
  end

  def edit
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:id])
  end

  def update
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:id])

    if @work.update(work_params)
      redirect_to author_work_path(@author, @work)
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:id])
    @work.destroy

    redirect_to @author
  end

  private
  def work_params
    params.require(:work).permit(:name, :author_id)
  end
end

app/views/works/_form.html.erb
<div class="wrapper">
  <%= simple_form_for [@author, @work], html: {class: "new-form"} do |f| %>
    <%= f.hidden_field :author_id, value: @author.id %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/works/edit.html.erb
<div class="banner">
  <div class="banner">
    <h1>Edit work</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/works/new.html.erb
<div class="banner">
  <div class="center">
    <h1>Add a new work</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/works/show.html.erb
<div class="banner">
  <div class="center">
    <h1><%= @work.name %></h1>
    <% if signed_in? %>
      <ul>
        <li><%= link_to "Edit work", edit_author_work_path %></li>
        <li><%= link_to "Delete work", author_work_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <li><%= link_to "Add chapter", new_author_work_chapter_path(@work.author, @work) %></li>
        <li><%= link_to "Add article", new_author_work_article_path(@work.author, @work) %></li>
      </ul>
    <% end %>
    <%= image_tag @work.author.bust.url(:normal) %>
  </div>
</div>

<div class="wrapper">
  <% @work.chapters.each do |chapter| %>
    <div class="chapter">
      <h1><%= link_to chapter.name, author_work_chapter_path(@work.author, @work, chapter) %></h1>
      <h2>Lines <%= chapter.start_line %> - <%= chapter.end_line %></h2>
    </div>
  <% end %>
</div>