config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/articles" => "articles#index", as: "articles"
  root 'authors#index'

  resources :authors do
    resources :works do
      resources :articles, except: [:index]
      resources :chapters do
        resources :sections
      end
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
  include Filterable
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :works, dependent: :destroy
  has_attached_file :bust, styles: { normal: "218x218>" }, default_url: "/images/plato.png"
  validates_attachment_content_type :bust, content_type: /\Aimage\/.*\z/

  scope :starts_with, -> (name) { where("name like ?", "#{name.capitalize}%") }

  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @authors = Author.filter(params.slice(:starts_with))
  end

  def show
    @author = Author.friendly.find(params[:id])
    @works = @author.works.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def edit
    @author = Author.friendly.find(params[:id])
  end

  def update
    @author = Author.friendly.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.friendly.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:name, :category, :bust)
  end
end

app/views/authors/_form.html.erb
<div class="wrapper">
  <%= simple_form_for @author, html: {class: "new-form"} do |f| %>
    <%= f.input :name %>
    <%= f.input :category, collection: ["Latin", "Greek"] %>
    <%= f.input :bust, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/authors/edit.html.erb
<div class="banner">
  <div class="center">
    <h1>Edit this author</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/authors/index.html.erb
<div class="banner">
  <div class="center">
    <h1>Study and learn from ancient texts</h1>
    <p>Sofia is an interactive study guide for students of the classics</p>
    <% if signed_in? %>
      <ul>
        <li><%= link_to "Add author", new_author_path %></li>
      </ul>
    <% end %>
    <%= image_tag "plato.png" %>
  </div>
</div>

<div class="wrapper">
  <%= simple_form_for :author, method: 'get', url: authors_path, html: {:class => 'author-search'} do |f| %>
    <%= f.input :starts_with, placeholder: "Search for author...", label: false, input_html: { autofocus: "true", name: 'starts_with' } %>
  <% end %>

  <% @authors.each do |author| %>
    <div class="author">
      <h1><%= link_to author.name.upcase, author_path(author) %></h1>
      <ul>
        <% author.works[0,20].each do |work| %>
          <li><%= link_to work.name, author_work_path(author, work) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class="banner">
  <div class="center">
    <h1>Add a new author</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/authors/show.html.erb
<div class="banner">
  <div class="center">
    <h1><%= @author.name %></h1>
    <% if signed_in? %>
      <ul>
        <li><%= link_to "Edit author", edit_author_path(@author) %></li>
        <li><%= link_to "Delete author", author_path(@author), method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <li><%= link_to "Add work", new_author_work_path(@author) %></li>
      </ul>
    <% end %>
    <%= image_tag @author.bust.url(:normal) %>
  </div>
</div>

<div class="wrapper">
  <% @works.each do |work| %>
    <div class="work">
      <h1><%= link_to work.name, author_work_path(@author, work)%></h1>
      <ul>
        <% work.chapters.each do |chapter| %>
          <li><%= link_to chapter.name, author_work_chapter_path(@author, work, chapter) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>