config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/articles" => "articles#index", as: "articles"
  root 'authors#index'

  resources :authors do
    resources :works do
      resources :articles, except: [:index]
      resources :chapters do
        resources :sections
      end
    end
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :work
  has_many :sections, dependent: :destroy
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :require_login, except: [:show]

  def show
    @chapter = Chapter.friendly.find(params[:id])
  end

  def new
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:work_id])
    @chapter = Chapter.new
  end

  def create
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:work_id])
    @chapter = Chapter.new(chapter_params)

    if @chapter.save
      redirect_to author_work_chapter_path(@work.author, @work, @chapter)
    else
      render 'new'
    end
  end

  def edit
    @chapter = Chapter.friendly.find(params[:id])
  end

  def update
    @author = Author.friendly.find(params[:author_id])
    @work = Work.friendly.find(params[:work_id])
    @chapter = Chapter.friendly.find(params[:id])

    if @chapter.update(chapter_params)
      redirect_to author_work_chapter_path(@work.author, @work, @chapter)
    else
      render 'edit'
    end
  end
  
  def destroy
    @work = Work.friendly.find(params[:work_id])
    @chapter = Chapter.friendly.find(params[:id])
    @chapter.destroy

    redirect_to author_work_path(@work.author, @work)
  end

  private
  def chapter_params
    params.require(:chapter).permit(:name, :work_id, :start_line, :end_line)
  end
end

app/views/chapters/_form.html.erb
<div class="wrapper">
  <%= simple_form_for [@author, @work, @chapter], html: {class: "new-form"} do |f| %>
    <%= f.hidden_field :work_id, value: @work.id %>
    <%= f.input :name %>
    <%= f.input :start_line %>
    <%= f.input :end_line %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/chapters/edit.html.erb
<div class="banner">
  <div class="center">
    <h1>Edit chapter</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/chapters/new.html.erb
<div class="banner">
  <div class="center">
    <h1>Add a new chapter</h1>
  </div>
</div>

<%= render partial: 'form' %>

app/views/chapters/show.html.erb
<div class="chapter-header">
  <h1><%= link_to @chapter.work.name, author_work_path(@chapter.work.author, @chapter.work) %></h1>
  <h2><%= @chapter.name %></h2>
  <div class="legend">
    <%= button_tag "Show structure", id: "switch" %>
    <div class="case-colors hidden">
      <div class="nom">Nominative</div>
      <div class="gen">Genitive</div>
      <div class="dat">Dative</div>
      <div class="acc">Accusative</div>
      <div class="abl">Ablative</div>
      <div class="adv">Adverb</div>
      <div class="verb">Verb</div>
      <div class="voc">Vocative</div>
    </div>
  </div>
  <% if signed_in? %>
    <h2>
      <%= button_to "Delete chapter", author_work_chapter_path, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= button_to "Add section", new_author_work_chapter_section_path(@chapter.work.author, @chapter.work, @chapter), method: :get %>
    </h2>
  <% end %>
</div>

<div class="chapter-navigation">
  <div class="center">
    <ul>
      <% ordered_sections = @chapter.sections.sort { |a,b| a.start_line <=> b.start_line } %>
      <% ordered_sections.each do |section| %>
        <li><%= link_to("#line-" + section.start_line.to_s) do %>
          <%= section.start_line.to_s.rjust(2, '0') %>-<%= section.end_line.to_s.rjust(2, '0') %>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="wrapper">
  <% ordered_sections.each do |section| %>
    <div id="line-<%=section.start_line %>" class="section">
      <div class="title">
        <h1><%= section.start_line.to_s.rjust(2, '0')%>-<%=section.end_line.to_s.rjust(2, '0') %></h1>
        <p><%= section.name.upcase %></p>
        <% if signed_in? %>
          <%= button_to "edit section", edit_author_work_chapter_section_path(section.chapter.work.author, section.chapter.work, section.chapter, section), method: :get %>
          <%= button_to "delete section", author_work_chapter_section_path(section.chapter.work.author, section.chapter.work, section.chapter, section), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <div class="original no-background" id="<%= section.start_line %>">
        <p><%= simple_format(section.original, {}, sanitize: false) %></p>
      </div>
      <div class="translation no-background" id="<%= section.start_line %>">
        <p><%= simple_format(section.translation, {}, sanitize: false) %></p>
      </div>
    </div>
  <% end %>
</div>